version: '3.8'
services: 
  ps2dev: 
    build: 
      context: . 
      dockerfile: Dockerfile
    volumes: 
      - ..:/workspace:cached
    working_dir: /workspace
    tty: true
    stdin_open: true
    network_mode: host